"""Tests for individual renderers."""
from __future__ import annotations

from pathlib import Path

import yaml

from doctyze import renderers


def test_registry_has_all_five_renderers() -> None:
    assert set(renderers.REGISTRY) == {
        "claude", "cursor", "copilot", "windsurf", "holmes",
    }


def test_registry_get_is_case_insensitive() -> None:
    assert isinstance(renderers.get("CLAUDE"), renderers.Renderer)
    assert isinstance(renderers.get("Claude"), renderers.Renderer)


def test_registry_get_unknown_raises_keyerror() -> None:
    try:
        renderers.get("definitely-not-a-vendor")
    except KeyError as exc:
        assert "definitely-not-a-vendor" in str(exc)
    else:
        raise AssertionError("expected KeyError")


# ── Claude renderer ────────────────────────────────────────────────────

def test_claude_renderer_creates_subdir_per_skill(fixture_repo: Path) -> None:
    r = renderers.get("claude")
    written = r.render(fixture_repo)
    assert len(written) == 1
    target = fixture_repo / ".claude" / "skills" / "write-adr" / "SKILL.md"
    assert target.exists()
    assert target in written


def test_claude_skill_md_preserves_name_and_description(fixture_repo: Path) -> None:
    renderers.get("claude").render(fixture_repo)
    content = (fixture_repo / ".claude" / "skills" / "write-adr" / "SKILL.md").read_text()
    # Frontmatter intact
    assert "name: write-adr" in content
    assert "description: Use when adding" in content
    # Body intact (banner is between frontmatter and body)
    assert "# How to write an ADR" in content
    # Generated banner so contributors know not to hand-edit
    assert "Generated by Doctyze" in content


def test_claude_renderer_dry_run_does_not_write(fixture_repo: Path) -> None:
    r = renderers.get("claude")
    written = r.render(fixture_repo, dry_run=True)
    assert len(written) == 1
    # The target was *named* but not created
    assert not (fixture_repo / ".claude" / "skills" / "write-adr" / "SKILL.md").exists()


# ── Cursor renderer ────────────────────────────────────────────────────

def test_cursor_renderer_writes_per_skill_file(fixture_repo: Path) -> None:
    renderers.get("cursor").render(fixture_repo)
    target = fixture_repo / ".cursor" / "rules" / "write-adr.md"
    assert target.exists()
    content = target.read_text()
    assert "# How to write an ADR" in content
    assert "Generated by Doctyze" in content


# ── Copilot renderer ───────────────────────────────────────────────────

def test_copilot_renderer_writes_single_concatenated_file(fixture_repo: Path) -> None:
    written = renderers.get("copilot").render(fixture_repo)
    assert len(written) == 1
    target = fixture_repo / ".github" / "copilot-instructions.md"
    assert target.exists()
    assert written == [target]
    content = target.read_text()
    assert "Copilot instructions" in content
    assert "write-adr" in content


def test_copilot_renderer_produces_stub_when_no_skills(tmp_path: Path) -> None:
    # Empty repo with no docs/skills/
    written = renderers.get("copilot").render(tmp_path)
    assert len(written) == 1
    content = written[0].read_text()
    assert "No canonical skills are defined yet" in content


# ── Windsurf renderer ──────────────────────────────────────────────────

def test_windsurf_renderer_writes_concatenated_file_at_root(fixture_repo: Path) -> None:
    written = renderers.get("windsurf").render(fixture_repo)
    assert len(written) == 1
    target = fixture_repo / ".windsurfrules"
    assert target.exists()
    assert written == [target]
    content = target.read_text()
    assert "Project rules for Windsurf" in content
    assert "write-adr" in content


# ── Holmes renderer ────────────────────────────────────────────────────

def test_holmes_renderer_writes_yaml_per_runbook(fixture_repo: Path) -> None:
    written = renderers.get("holmes").render(fixture_repo)
    assert len(written) == 1
    target = fixture_repo / ".holmes" / "runbooks" / "high-error-rate.yaml"
    assert target.exists()
    assert written == [target]


def test_holmes_renderer_produces_valid_yaml_with_expected_shape(fixture_repo: Path) -> None:
    renderers.get("holmes").render(fixture_repo)
    target = fixture_repo / ".holmes" / "runbooks" / "high-error-rate.yaml"
    parsed = yaml.safe_load(target.read_text())
    assert parsed["apiVersion"] == "holmesgpt/v1"
    assert parsed["kind"] == "Runbook"
    assert parsed["metadata"]["service"] == "orders-api"
    assert parsed["metadata"]["runbook_id"] == "high-error-rate"
    assert parsed["spec"]["match"]["alert_names"] == ["OrdersApiHighErrorRate"]
    assert parsed["spec"]["match"]["labels"]["severity"] == "high"
    assert parsed["spec"]["read_only"] is True
    # Body content lifted into instructions
    assert "5xx rate" in parsed["spec"]["instructions"]


def test_holmes_falls_back_to_filename_stem_when_no_runbook_id(tmp_path: Path) -> None:
    """If frontmatter is missing runbook_id, use the file stem."""
    rb_dir = tmp_path / "docs" / "runbooks"
    rb_dir.mkdir(parents=True)
    (rb_dir / "no-id.md").write_text(
        "---\nservice: foo\nseverity: medium\n---\nBody.\n"
    )
    written = renderers.get("holmes").render(tmp_path)
    assert written[0].name == "no-id.yaml"
