"""Renderer base class + shared helpers for parsing canonical markdown."""
from __future__ import annotations

import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml


@dataclass
class CanonicalDoc:
    """A parsed canonical markdown file with YAML frontmatter."""

    path: Path
    frontmatter: dict[str, Any] = field(default_factory=dict)
    body: str = ""

    @property
    def name(self) -> str:
        """Stable identifier — frontmatter `name` if present, else filename stem."""
        return str(self.frontmatter.get("name") or self.path.stem)


_FRONTMATTER_RE = re.compile(
    r"\A---\s*\n(.*?)\n---\s*\n(.*)\Z",
    re.DOTALL,
)


def parse_canonical(path: Path) -> CanonicalDoc:
    """Parse a canonical markdown file (optional YAML frontmatter + markdown body)."""
    text = path.read_text()
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return CanonicalDoc(path=path, frontmatter={}, body=text)
    raw_fm, body = m.group(1), m.group(2)
    try:
        fm = yaml.safe_load(raw_fm) or {}
        if not isinstance(fm, dict):
            fm = {}
    except yaml.YAMLError:
        fm = {}
    return CanonicalDoc(path=path, frontmatter=fm, body=body)


def collect_canonical(repo_root: Path, subdir: str) -> list[CanonicalDoc]:
    """Collect all canonical .md files under `<repo_root>/docs/<subdir>/`."""
    base = repo_root / "docs" / subdir
    if not base.is_dir():
        return []
    return [parse_canonical(p) for p in sorted(base.glob("*.md"))]


class Renderer(ABC):
    """Base class for vendor-specific renderers.

    Subclasses set :attr:`name` and implement :meth:`render`. Each renderer
    returns the list of files it generated (or would generate in dry-run).
    """

    #: Vendor identifier — lowercase, no spaces.
    name: str = ""
    #: Human-readable description for `doctyze render --list`.
    description: str = ""

    @abstractmethod
    def render(
        self,
        repo_root: Path,
        *,
        dry_run: bool = False,
    ) -> list[Path]:
        """Render canonical content → vendor-specific files under repo_root.

        Args:
            repo_root: Root of the repository whose canonical sources we read.
            dry_run: If True, do not write files; just compute the would-be targets.

        Returns:
            List of paths that were (or would be) written.
        """

    # ── shared utilities for subclasses ──

    @staticmethod
    def _write(target: Path, content: str, dry_run: bool) -> Path:
        """Write content to target, creating parents. No-op when dry_run."""
        if dry_run:
            return target
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        return target

    @staticmethod
    def _generated_banner(canonical_relpath: str) -> str:
        """Standard banner stamped on top of generated files."""
        return (
            f"<!-- Generated by Doctyze from {canonical_relpath}. "
            f"Do not edit by hand — edit the canonical source. -->\n\n"
        )
