"""HolmesGPT runbooks renderer.

Reads canonical `docs/runbooks/*.md` (markdown + YAML frontmatter) and emits
HolmesGPT-format YAML at `.holmes/runbooks/<runbook_id>.yaml`.

Frontmatter convention for canonical runbooks:

    ---
    runbook_id: high-error-rate
    alert_names: ["MyServiceHighErrorRate"]
    severity: high
    service: my-service
    confidence: confirmed | inferred | gap
    ---

The markdown body becomes the `instructions:` field on the Holmes runbook.
"""
from __future__ import annotations

from pathlib import Path

import yaml

from doctyze.renderers.base import CanonicalDoc, Renderer, collect_canonical


class HolmesRenderer(Renderer):
    name = "holmes"
    description = "HolmesGPT — .holmes/runbooks/<id>.yaml (per-runbook YAML)"

    def render(self, repo_root: Path, *, dry_run: bool = False) -> list[Path]:
        runbooks = collect_canonical(repo_root, "runbooks")
        written: list[Path] = []
        for rb in runbooks:
            runbook_id = rb.frontmatter.get("runbook_id") or rb.path.stem
            target = repo_root / ".holmes" / "runbooks" / f"{runbook_id}.yaml"
            content = self._build_holmes_yaml(rb, runbook_id)
            written.append(self._write(target, content, dry_run))
        return written

    def _build_holmes_yaml(self, rb: CanonicalDoc, runbook_id: str) -> str:
        fm = rb.frontmatter
        service = fm.get("service", "{{SERVICE_NAME}}")
        alert_names = fm.get("alert_names") or [f"{service}{runbook_id.title().replace('-', '')}"]
        severity = fm.get("severity", "medium")

        # Strip the human-readable confidence callout from the body for the
        # instructions field — keep it focused on actionable steps.
        instructions = self._extract_instructions(rb.body)

        doc = {
            "apiVersion": "holmesgpt/v1",
            "kind": "Runbook",
            "metadata": {
                "service": service,
                "runbook_id": runbook_id,
            },
            "spec": {
                "match": {
                    "labels": {
                        "service": service,
                        "severity": severity,
                    },
                    "alert_names": alert_names,
                },
                "instructions": instructions,
                "read_only": True,
            },
        }

        banner = (
            "# Generated by Doctyze from docs/runbooks/"
            f"{rb.path.name}\n"
            "# Do not edit by hand — edit the canonical markdown.\n\n"
        )
        return banner + yaml.safe_dump(doc, sort_keys=False)

    @staticmethod
    def _extract_instructions(body: str) -> str:
        """Lift only the actionable sections from the canonical body.

        Keep the body wholesale for v0.0.2 — the LLM driving HolmesGPT can
        parse markdown headers fine. Future versions can extract specific
        sections (Diagnostic steps, Remediations) more aggressively.
        """
        return body.strip()
