"""Build navigation indexes — a table of contents for humans and agents.

Deterministic, no LLM: reads each doc's H1 title + first summary line and writes
a per-section `index.md` table plus a top-level `docs/index.md`. Re-run any time
(`doctyze index`); it just reflects whatever docs exist.
"""
from __future__ import annotations

import re
from pathlib import Path

from ..config import SECTIONS

_H1 = re.compile(r"^#\s+(.+)$", re.M)
_BANNER = "<!-- generated by `doctyze index` — do not edit by hand -->"


def _title_and_summary(text: str) -> tuple[str | None, str]:
    body = text
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            body = parts[2]
    m = _H1.search(body)
    if not m:
        return None, ""
    title = m.group(1).strip()
    for line in body[m.end():].splitlines():
        s = line.strip()
        if not s or s.startswith(("#", ">", "|", "```", "<!--")):
            continue
        if set(s) <= {"-", "=", "*", "_"}:  # separator / rule line
            continue
        if s.lower().startswith(("**status:**", "status:")):  # ADR header line — keep scanning for the gist
            continue
        s = s.rstrip(".")
        if len(s) > 140:
            s = s[:140].rstrip() + "…"
        return title, s
    return title, ""


def build_indexes(root: str | Path) -> list[Path]:
    root = Path(root).resolve()
    docs_dir = root / "docs"
    if not docs_dir.exists():
        return []

    written: list[Path] = []
    present: list[tuple[str, object, int]] = []

    for key, section in SECTIONS.items():
        d = root / section.path
        if not d.exists():
            continue
        files = sorted(p for p in d.glob("*.md") if p.name != "index.md")
        rows = []
        for f in files:
            try:
                title, summary = _title_and_summary(f.read_text(encoding="utf-8"))
            except (OSError, UnicodeDecodeError):
                title, summary = None, ""
            rows.append(f"| [{title or f.stem}]({f.name}) | {summary} |")
        lines = [_BANNER, f"# {key.title()}", "", section.blurb, ""]
        lines += (["| Doc | Summary |", "|---|---|", *rows] if rows else ["_No documents yet._"])
        (d / "index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
        written.append(d / "index.md")
        present.append((key, section, len(files)))

    top = [
        _BANNER, "# Documentation", "",
        "Maintained by Doctyze. Navigate by section:", "",
        "| Section | Docs | About |", "|---|---|---|",
    ]
    for key, section, n in present:
        rel = Path(section.path).relative_to("docs").as_posix()
        top.append(f"| [{key.title()}]({rel}/index.md) | {n} | {section.blurb} |")
    (docs_dir / "index.md").write_text("\n".join(top) + "\n", encoding="utf-8")
    written.append(docs_dir / "index.md")
    return written
