"""Build navigation indexes — a table of contents for humans and agents.

Deterministic, no LLM: reads each doc's H1 title + first summary line and writes
a per-section `index.md` table plus a top-level `docs/index.md`. Re-run any time
(`doctyze index`); it just reflects whatever docs exist.
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml

from ..config import SECTIONS

_H1 = re.compile(r"^#\s+(.+)$", re.M)
_BANNER = "<!-- generated by `doctyze index` — do not edit by hand -->"


def _sidebar_position(text: str) -> float:
    """Read `sidebar_position` from YAML frontmatter for ordering. Missing/invalid -> +inf (sorts last)."""
    if not text.startswith("---"):
        return float("inf")
    parts = text.split("---", 2)
    if len(parts) < 3:
        return float("inf")
    try:
        data = yaml.safe_load(parts[1])
    except yaml.YAMLError:
        return float("inf")
    if not isinstance(data, dict):
        return float("inf")
    try:
        return float(data["sidebar_position"])
    except (KeyError, TypeError, ValueError):
        return float("inf")


def _title_and_summary(text: str) -> tuple[str | None, str]:
    body = text
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            body = parts[2]
    m = _H1.search(body)
    if not m:
        return None, ""
    title = m.group(1).strip()
    for line in body[m.end():].splitlines():
        s = line.strip()
        if not s or s.startswith(("#", ">", "|", "```", "<!--")):
            continue
        if set(s) <= {"-", "=", "*", "_"}:  # separator / rule line
            continue
        if s.lower().startswith(("**status:**", "status:")):  # ADR header line — keep scanning for the gist
            continue
        s = s.rstrip(".")
        if len(s) > 140:
            s = s[:140].rstrip() + "…"
        return title, s
    return title, ""


def build_indexes(root: str | Path) -> list[Path]:
    root = Path(root).resolve()
    docs_dir = root / "docs"
    if not docs_dir.exists():
        return []

    written: list[Path] = []
    present: list[tuple[str, object, int]] = []

    for key, section in SECTIONS.items():
        d = root / section.path
        if not d.exists():
            continue
        # Order by `sidebar_position` frontmatter (what the published sidebar uses),
        # then by filename as a stable tiebreak. Docs without a position sort last.
        entries = []
        for f in d.glob("*.md"):
            if f.name == "index.md":
                continue
            try:
                text = f.read_text(encoding="utf-8")
                title, summary = _title_and_summary(text)
                pos = _sidebar_position(text)
            except (OSError, UnicodeDecodeError):
                title, summary, pos = None, "", float("inf")
            entries.append((pos, f.name, title, summary))
        entries.sort(key=lambda e: (e[0], e[1]))
        rows = [f"| [{title or Path(name).stem}]({name}) | {summary} |"
                for _pos, name, title, summary in entries]
        lines = [_BANNER, f"# {key.title()}", "", section.blurb, ""]
        lines += (["| Doc | Summary |", "|---|---|", *rows] if rows else ["_No documents yet._"])
        (d / "index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
        written.append(d / "index.md")
        present.append((key, section, len(entries)))

    top = [
        _BANNER, "# Documentation", "",
        "Maintained by Doctyze. Navigate by section:", "",
        "| Section | Docs | About |", "|---|---|---|",
    ]
    for key, section, n in present:
        rel = Path(section.path).relative_to("docs").as_posix()
        top.append(f"| [{key.title()}]({rel}/index.md) | {n} | {section.blurb} |")
    (docs_dir / "index.md").write_text("\n".join(top) + "\n", encoding="utf-8")
    written.append(docs_dir / "index.md")
    return written
