"""Build the bootstrap manifest — the to-do list the existing agent works from.

Doctyze (deterministic) scaffolds structure and decides WHAT should exist; the
agent (LLM) generates the prose grounded in the code. The manifest is the
handoff between the two.
"""
from __future__ import annotations

from pathlib import Path

from ..consolidate.audit import discover
from ..freshness.anchors import parse_anchor
from .stack import Stack


def _existing_docs(root: Path) -> list[str]:
    """Docs already present that Doctyze did NOT generate — refresh, don't duplicate."""
    out: list[str] = []
    for f in discover(root / "docs") if (root / "docs").exists() else []:
        if f.name == "index.md":
            continue
        try:
            if parse_anchor(f.read_text(encoding="utf-8")) is None:  # no doctyze anchor = pre-existing
                out.append(str(f.relative_to(root)))
        except (OSError, UnicodeDecodeError):
            continue
    return sorted(out)

# Each entry: (skill the agent runs, what it produces).
_PLAN = [
    ("write-architecture", "docs/architecture/overview.md + Mermaid diagrams in docs/architecture/diagrams/"),
    ("write-spec", "one spec per major feature in docs/specs/"),
    ("write-functional-spec", "one product-owner-facing functional spec per capability in docs/functional-specs/ (user stories + acceptance criteria), each tied to its technical spec"),
    ("write-runbook", "operational + deployment runbooks in docs/runbooks/"),
    ("write-observability", "incident/observability docs in docs/observability/"),
    ("write-skills", "dev & testing skills/rules for this stack in docs/skills/"),
]


def build_manifest(root: str | Path, stack: Stack, diagrams_done: bool) -> str:
    langs = ", ".join(stack.languages) or "unknown"
    fw = ", ".join(stack.frameworks) or "—"
    lines = [
        "# Doctyze bootstrap manifest",
        "",
        f"**Stack:** {langs}  |  **Frameworks:** {fw}  |  "
        f"**CI:** {', '.join(stack.ci) or '—'}  |  **Deploy:** {', '.join(stack.deploy) or '—'}",
        "",
        "The canonical `docs/` structure has been scaffolded. Now generate each",
        "artifact below by running the matching skill — grounded in the actual code,",
        "and add a Doctyze freshness anchor to every file you create.",
        "",
        "| Skill | Produces |",
        "|---|---|",
    ]
    for skill, produces in _PLAN:
        if skill == "write-architecture" and diagrams_done:
            produces += " (diagrams already generated by CodeBoarding — write the prose)"
        lines.append(f"| `{skill}` | {produces} |")
    existing = _existing_docs(Path(root).resolve())
    if existing:
        lines += [
            "",
            "## Existing docs — refresh or split, do NOT duplicate",
            "These already exist (consolidated, not Doctyze-generated). Before writing a",
            "new doc on the same topic, refresh/split these and cite them — don't write a",
            "parallel copy:",
            "",
        ]
        lines += [f"- `{p}`" for p in existing[:40]]
        if len(existing) > 40:
            lines.append(f"- … and {len(existing) - 40} more")

    lines += [
        "",
        "Keep every doc's `affects:` anchor narrow (the specific module(s), not `app/**`).",
        "After generating, run `doctyze distribute` and `doctyze watch --install`.",
        "",
    ]
    return "\n".join(lines)
