"""Build the bootstrap manifest — the to-do list the existing agent works from.

Doctyze (deterministic) scaffolds structure and decides WHAT should exist; the
agent (LLM) generates the prose grounded in the code. The manifest is the
handoff between the two.
"""
from __future__ import annotations

from pathlib import Path

from .stack import Stack

# Each entry: (skill the agent runs, what it produces).
_PLAN = [
    ("write-architecture", "docs/architecture/overview.md + Mermaid diagrams in docs/architecture/diagrams/"),
    ("write-spec", "one spec per major feature in docs/specs/"),
    ("write-runbook", "operational + deployment runbooks in docs/runbooks/"),
    ("write-observability", "incident/observability docs in docs/observability/"),
    ("write-skills", "dev & testing skills/rules for this stack in docs/skills/"),
]


def build_manifest(root: str | Path, stack: Stack, diagrams_done: bool) -> str:
    langs = ", ".join(stack.languages) or "unknown"
    fw = ", ".join(stack.frameworks) or "—"
    lines = [
        "# Doctyze bootstrap manifest",
        "",
        f"**Stack:** {langs}  |  **Frameworks:** {fw}  |  "
        f"**CI:** {', '.join(stack.ci) or '—'}  |  **Deploy:** {', '.join(stack.deploy) or '—'}",
        "",
        "The canonical `docs/` structure has been scaffolded. Now generate each",
        "artifact below by running the matching skill — grounded in the actual code,",
        "and add a Doctyze freshness anchor to every file you create.",
        "",
        "| Skill | Produces |",
        "|---|---|",
    ]
    for skill, produces in _PLAN:
        if skill == "write-architecture" and diagrams_done:
            produces += " (diagrams already generated by CodeBoarding — write the prose)"
        lines.append(f"| `{skill}` | {produces} |")
    lines += [
        "",
        "After generating, run `doctyze distribute` to fan the skills out to your",
        "agent files, and `doctyze watch --install` to keep everything fresh.",
        "",
    ]
    return "\n".join(lines)
