/*
 * Structurizr C4 model for {{SERVICE_NAME}}.
 * Source-of-truth architecture. Mermaid diagrams in diagrams/ are derived.
 *
 * Render locally:
 *   docker run --rm -p 8080:8080 -v "$PWD:/usr/local/structurizr" structurizr/lite
 *   # open http://localhost:8080
 *
 * Confidence: 🟡 INFERRED. Generated by Doctyze; verify against actual deployment.
 */

workspace "{{SERVICE_NAME}}" "{{ONE_LINE_DESCRIPTION}}" {

    model {
        user = person "User" "Primary user of the service"

        system = softwareSystem "{{SERVICE_NAME}}" "{{ONE_LINE_DESCRIPTION}}" {
            // TODO: list containers (web, api, worker, db, cache, etc.)
            //
            // Example:
            // web = container "{{SERVICE_NAME}} Web" "Browser SPA" "React"
            // api = container "{{SERVICE_NAME}} API" "REST endpoints" "{{LANGUAGE}}"
            // db  = container "Database" "Relational store" "PostgreSQL" {
            //     tags "Database"
            // }
        }

        // External systems this depends on (auth, payment, observability, ...)
        // externalAuth = softwareSystem "Identity Provider" "Authn / Authz" {
        //     tags "External"
        // }

        // Relationships
        // user -> web "Uses" "HTTPS"
        // web  -> api "Calls" "HTTPS / JSON"
        // api  -> db  "Reads/writes" "SQL"
    }

    views {
        systemContext system "SystemContext" { include *; autolayout lr }
        container     system "Container"     { include *; autolayout lr }
        // Add a dynamic view per critical flow:
        // dynamic system "Sequence-Checkout" "Checkout happy path" {
        //     user -> web "Submits order"
        //     web  -> api "POST /checkout"
        //     api  -> db  "Persist order"
        //     autolayout lr
        // }

        styles {
            element "External" { background "#888888" color "#ffffff" }
            element "Database" { shape Cylinder }
        }
    }
}
